Add support for fitBounds on V2.0.X
xdev-software/vaadin-maps-leaflet-flow pull request #204
Opened 2023-01-20 09:58 UTC by echarlus

After discussing my initial PR (#155) which was based on old code, I've re-implemented the changes on top of 2.0.3 version for Vaadin 23.3.
This change allows to automatically center & zoom the map based on a rectangular area which is useful if you want to optimize the view on a specific automatically

2023-01-25 10:26 UTC, JohannesRabauer requested changes
Please fix these minor changes, then we can merge the branch. :)

2023-01-25 10:26 UTC, JohannesRabauer commented on vaadin-maps-leaflet-flow-demo/pom.xml
> +			<plugin>
This change is uneccessary.

2023-01-25 10:26 UTC, JohannesRabauer commented on vaadin-maps-leaflet-flow/pom.xml
> +			<plugin>
The component is packaged as a jar. There is no need to add the maven-war-plugin. Please delete this change.

2023-01-25 10:26 UTC, JohannesRabauer commented on vaadin-maps-leaflet-flow/src/main/java/software/xdev/vaadin/maps/leaflet/flow/LMap.java
> +	public void centerAndZoom(final LPoint noPoint, final LPoint sePoint)
Please add a minimal description. Maybe add the link to https://leafletjs.com/reference.html#map-fitbounds.
noPoint and sePoint seems not very descriptive.

2023-01-25 10:26 UTC, JohannesRabauer commented on vaadin-maps-leaflet-flow/src/main/java/software/xdev/vaadin/maps/leaflet/flow/data/LPoint.java
> +		coords.add(lat);
"this." should be added automatically through intellij. Please delete this change.

2023-01-25 10:26 UTC, JohannesRabauer commented on vaadin-maps-leaflet-flow/src/main/java/software/xdev/vaadin/maps/leaflet/flow/data/LPoint.java
> +		coords.add(lon);
"this." should be added automatically through intellij. Please delete this change.

2023-01-25 10:26 UTC, JohannesRabauer commented on vaadin-maps-leaflet-flow/src/main/java/software/xdev/vaadin/maps/leaflet/flow/data/LPoint.java
> +		return coords.get(0);
"this." should be added automatically through intellij. Please add "this." in front of coords.

2023-01-25 10:26 UTC, JohannesRabauer commented on vaadin-maps-leaflet-flow/src/main/java/software/xdev/vaadin/maps/leaflet/flow/data/LPoint.java
> +		return coords.get(1);
"this." should be added automatically through intellij. Please add "this." in front of coords.

2023-01-28 10:49 UTC, echarlus commented
@JohannesRabauer I've pushed the requested changes to my develop branch. Let me know if it's ok.
Thanks

2023-01-30 06:44 UTC, merged